name: 'Pushing Hours Restriction'
description: 'Add pushing hours restriction to the Branch protection rule of the default branch'
author: 'hamuyuuki'
branding:
  icon: 'calendar'
  color: 'green'
inputs:
  app_id:
    required: true
    description: 'If you authenticate with a GitHub App, you should set this input. You can set App Id of your GitHub App.'
  private_key:
    required: true
    description: 'If you authenticate with a GitHub App, you should set this input. You can set Private key of your GitHub App.'
  weekdays:
    required: false
    default: 'MON,TUE,WED,THU'
    description: "You can set a comma delimited short weekday (e.g. 'MON,TUE'). When you set a value to weekdays, you can enable pushing hours on that weekdays."
  start_hour:
    required: true
    description: 'You can set a start of pushing hours.'
  end_hour:
    required: true
    description: 'You can set an end of pushing hours.'
  time_zone:
    required: false
    default: 'Etc/UTC'
    description: "You can set an IANA time zone name (e.g. 'Asia/Tokyo'). When you set a value to time_zone, you can enable pushing hours with that time zone."
  holiday:
    required: false
    default: ''
    description: "You can set a 2 digit country code (e.g. 'JP'). When you set a value to holiday, you can not enable pushing hours on that holiday and a day before that holiday."
runs:
  using: 'node16'
  main: 'dist/index.js'
